In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('teachers_dashboard_2024.csv')
df_pred = pd.read_csv('teachers_2024_attrition_predictions.csv')

df_pred['is_out_next_year'] = df_pred['risk_level'].apply(lambda x: 1 if x == 'High' else 0)
df_pred.head()

,id,attrition_probability,predicted_attrition,risk_level,is_out_next_year
0,0000c29d68,0.113243,1,Low,0
1,00081033d0,0.552200,1,High,1
2,000d0f08a6,0.055342,0,Low,0
3,000ee8f2b6,0.049753,0,Low,0
4,00106cc362,0.052808,0,Low,0

In [6]:
df.update(df_pred[['is_out_next_year']])

In [16]:
df_ml = pd.read_csv('teachers_ml_yearly_enriched.csv')
df['has_higher_edu'] = df['id'].map(df_ml['has_higher_edu'])

In [15]:
df_ml

,id,year,school_num,main_position,speciality,sex,age,academic_degree,category_qual,category_due,...,studied_in_moscow_any,school_known,pkpp_total_courses,has_prestigious_university,pkpp_unique_types,attrition_rate_2022,has_higher_edu,load_vs_district,school_size_deviation,pkpp_prog_types_2023
0,0000c29d68,2022,121,Учитель,английского языка,0,26,NaN,Первая категория,2026.0,...,1.0,1.0,4.0,0.0,1.0,0.119565,1.0,0.097873,-0.008310,1.0
1,0000c29d68,2023,121,Учитель,английского языка,0,27,NaN,Первая категория,2026.0,...,1.0,1.0,4.0,0.0,1.0,0.119565,1.0,0.097873,-0.008310,1.0
2,0000c29d68,2024,121,Учитель,английского языка,0,28,NaN,Высшая категория,2028.0,...,1.0,1.0,4.0,0.0,1.0,0.119565,1.0,0.097873,-0.008310,1.0
3,00081033d0,2024,147,Советник директора по воспитанию и взаимодейст...,NaN,1,31,NaN,Первая категория,2027.0,...,0.0,1.0,1.0,1.0,1.0,0.156977,1.0,-0.014928,0.624642,1.0
4,000d0f08a6,2022,229,Учитель иностранного языка,NaN,0,49,NaN,Высшая категория,2026.0,...,1.0,1.0,2.0,0.0,1.0,0.095238,1.0,0.233239,-0.462945,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53995,fff7221340,2024,172,Учитель,английского языка,0,28,NaN,Первая категория,NaN,...,1.0,1.0,4.0,0.0,1.0,0.153846,1.0,-0.118481,-0.439480,1.0
53996,fff96a9229,2022,124,Учитель,NaN,0,30,NaN,Первая категория,2024.0,...,0.0,1.0,1.0,0.0,1.0,0.115385,1.0,-0.123529,-0.204420,0.0
53997,fff96a9229,2023,124,Учитель,истории,0,31,NaN,Первая категория,2024.0,...,0.0,1.0,1.0,0.0,1.0,0.115385,1.0,-0.123529,-0.204420,0.0
53998,fff96a9229,2024,124,Учитель,истории,0,32,NaN,Первая категория,2024.0,...,0.0,1.0,1.0,0.0,1.0,0.115385,1.0,-0.123529,-0.204420,0.0
53999,fff9bdf607,2024,497,Учитель,начальных классов,0,22,NaN,NaN,NaN,...,1.0,1.0,0.0,0.0,0.0,0.111111,0.0,-0.061219,-0.156056,0.0

In [19]:

df1 = pd.merge(df, df_ml[['id', 'has_higher_edu']], on='id', how='left')
df1

,id,school_num,main_position,speciality,sex,age,academic_degree,category_qual,category_due,experience_age_all,...,parallels,n_unique_subjects,min_parallel,max_parallel,n_unique_parallel,is_critical,class_manager,n_unique_subjects_log,has_higher_edu_x,has_higher_edu_y
0,0000c29d68,121,Учитель,английского языка,0,28,NaN,Высшая категория,2028.0,7,...,7,1,7,7,1,False,1,0.693147,NaN,1.0
1,0000c29d68,121,Учитель,английского языка,0,28,NaN,Высшая категория,2028.0,7,...,7,1,7,7,1,False,1,0.693147,NaN,1.0
2,0000c29d68,121,Учитель,английского языка,0,28,NaN,Высшая категория,2028.0,7,...,7,1,7,7,1,False,1,0.693147,NaN,1.0
3,00081033d0,147,Советник директора по воспитанию и взаимодейст...,NaN,1,31,NaN,Первая категория,2027.0,5,...,8,1,8,8,1,False,0,0.693147,NaN,1.0
4,000d0f08a6,229,Учитель,английского языка,0,51,NaN,Высшая категория,2026.0,32,...,3,1,3,3,1,False,0,0.693147,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48330,fff7221340,172,Учитель,английского языка,0,28,NaN,Первая категория,NaN,6,...,2,1,2,2,1,False,0,0.693147,NaN,1.0
48331,fff96a9229,124,Учитель,истории,0,32,NaN,Первая категория,2024.0,10,...,5,1,5,5,1,False,1,0.693147,NaN,1.0
48332,fff96a9229,124,Учитель,истории,0,32,NaN,Первая категория,2024.0,10,...,5,1,5,5,1,False,1,0.693147,NaN,1.0
48333,fff96a9229,124,Учитель,истории,0,32,NaN,Первая категория,2024.0,10,...,5,1,5,5,1,False,1,0.693147,NaN,1.0
48334,fff9bdf607,497,Учитель,начальных классов,0,22,NaN,NaN,NaN,3,...,1,1,1,1,1,False,1,0.693147,NaN,0.0

In [22]:
# del df1['has_higher_edu_x']

df1.rename(columns={'has_higher_edu_y': 'has_higher_edu'}, inplace=True)
df1.to_csv('teachers_dashboard_2024.csv')